In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)

C

array([[0.80475509, 0.90512895, 0.23808652, 0.94734501, 0.37830657],
       [0.02190019, 0.55890014, 0.76382358, 0.7295035 , 0.92503841],
       [0.9510704 , 0.4723756 , 0.88855083, 0.73942222, 0.62139201]])

In [6]:
D = np.zeros((2, 4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
A[0][2]

2