In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
    ])
B = np.random.rand(3, 3)

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
B

array([[0.4778973 , 0.7596493 , 0.46084463],
       [0.27483039, 0.84528637, 0.64596842],
       [0.56544008, 0.44194857, 0.79725374]])

In [5]:
A + B

array([[ 1.4778973 , -0.2403507 ,  2.46084463],
       [ 3.27483039,  2.84528637,  2.64596842],
       [ 4.56544008,  1.44194857,  2.79725374]])

In [6]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [8]:
np.dot(A, B) # 곱

array([[1.33394706, 0.79826007, 1.40938369],
       [3.11423283, 4.8534178 , 4.26897821],
       [3.31729973, 4.76778072, 4.08385443]])

In [9]:
A @ B # 곱

array([[1.33394706, 0.79826007, 1.40938369],
       [3.11423283, 4.8534178 , 4.26897821],
       [3.31729973, 4.76778072, 4.08385443]])

In [10]:
A @ B + (A + 2 * B)

array([[3.28974165, 1.31755868, 4.33107295],
       [6.66389362, 8.54399054, 7.56091505],
       [8.44817989, 6.65167787, 7.6783619 ]])