In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
A_transpose = np.transpose(A)
A_transpose # 전치행렬

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [5]:
A.T #더 간단한 방법

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [6]:
I = np.identity(3) # 단위행렬 만들어주기 

In [7]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [9]:
np.linalg.pinv(A) # 역행렬 

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [10]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [11]:
A @ A_inverse # 

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 2.22044605e-16,  2.22044605e-16,  1.00000000e+00]])