In [5]:
import numpy as np

In [6]:
array1 = np.array([2, 3, 5, 7, 9, 10, 12, 13])

In [3]:
array1[2]

5

In [4]:
array1[-1]

13

In [5]:
array1[-2]

12

In [7]:
array1[[1, 3, 4]]

array([3, 7, 9])

[]안에 또다른 []를 넣을 수 있다. 

In [7]:
array2 = np.array([2, 1, 3])

In [11]:
array1[array2]

array([5, 3, 7])

In [12]:
array1[2:7]

array([ 5,  7,  9, 10, 12])

In [13]:
array1[:7]

array([ 2,  3,  5,  7,  9, 10, 12])

In [14]:
array1[2:]

array([ 5,  7,  9, 10, 12, 13])

In [16]:
array1[2:10:2]

array([ 5,  9, 12])

In [10]:
array1[[2, 3]]

array([5, 7])