In [1]:
import numpy as np

In [4]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [5]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
 for i in range(len(array1)): 
        array1[i] = 2 * array1[i]

일반적인 파이선일 경우의 방법

In [9]:
array1 * 2 

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

아주 간단 

In [10]:
array1 / 2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
array1 ** 2 

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324], dtype=int32)

In [12]:
array1 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

저장을 해줘야 이어짐 

In [13]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [14]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

**매우 간단** 

같은 위치에 있는 것을 곱하거나 더하거나 다 됌 