In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

간단한 `불린 연산` 가능

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [6]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True]) 

In [7]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

numpy 모듈 안에 `where` 함수를 쓰면 `True`값이 있는 리스트의 **인덱스** 값만  보여줌 

In [9]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [10]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])