In [1]:
import numpy as np 

In [2]:
data1 = [6, 7.5, 8, 0, 1]

In [4]:
arr1 = np.array(data1)

In [5]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
arr1.shape

(5,)

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

arr2는 2 x 4짜리 array가 되는 것

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((6))

array([1., 1., 1., 1., 1., 1.])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [23]:
arr = np.array([1, 2, 3, 4, 5], dtype = np.int64)

In [25]:
arr.dtype

dtype('int64')

기존의 array 데이터형을 변환하여 새로운 array를 만들 수 있다.  
astype(np.바꿀데이터형 64)

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
float_arr.dtype

dtype('float64')

In [30]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float64)

In [31]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]], dtype = np.float64)

In [32]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [34]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [35]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])